title: ""
description: Scientific illustration and visual design
url: "https://lorenajs.github.io"

theme: jekyll-theme-primer

plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown

sass:
  style: compressed
